### ISSUE TITLE
footerdagi ikonkalarni margini to'grilash

### ISSUE THREAD

**Issue by Andarov** [akramjonnuriddinov/Akademnashr-002#15]
`footer`dagi ikonkalarni faqat o'ng tarafidan bering qolgan tarafdan marginini 0 qilib qo'ying

**Comment by akramjonnuriddinov** [comment]
https://prnt.sc/I8yY9364JeR8 Mana faqat o'ng tarafda turibdi. Qolgan tarafida margin yo'q.
