### ISSUE TITLE
site-headerda marginni to'grilash

### ISSUE THREAD

**Issue by Andarov** [akramjonnuriddinov/Akademnashr-002#2]
`nav list`ni marginini 0 qilib. `basic-btn`ga chap tarafdan margin bering

**Comment by akramjonnuriddinov** [comment]
`basic-btn` ni 3 ta joyda ishlatganim uchun faqat buttonni yasab olish uchun kerak bo'ladigan stillarni `basic-btn` ga berdim. Yo'q bu buttonni qolgan joyda ishlatsam margin halaqit beradi.
